apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ballast
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ballast.bonny.run
  resources:
  - poolpolicies
  verbs:
  - "*"
- apiGroups:
  - ballast.bonny.run
  resources:
  - evictionpolicies
  verbs:
  - "*"  
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ''
  resources:
  - pods/eviction
  verbs:
  - create
