apiVersion: apps/v1
kind: Deployment
metadata:
  name: ballast
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    spec:
      volumes:
      - name: ballast-operator-sa-keys
        secret:
          secretName: ballast-operator-sa-keys
      containers:
      - name: ballast
        image: quay.io/coryodaniel/ballast
        env:
        - name: BALLAST_METRICS_PORT
          value: "9323"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/gcp.json
        - name: MIX_ENV
          value: prod
        - name: BONNY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BONNY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BONNY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BONNY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 15
        ports:
        - containerPort: 9323
          name: metrics
        volumeMounts:
        - name: ballast-operator-sa-keys
          mountPath: /credentials
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
      serviceAccountName: ballast
