apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  k8s-app: ballast
resources:
- custom_resource_definition.yaml
- pod_disruption_budget.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- service_account.yaml
- deployment.yaml
- service.yaml
