apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ballast
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      k8s-app: ballast
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    k8s-app: ballast
  name: poolpolicies.ballast.bonny.run
spec:
  group: ballast.bonny.run
  names:
    kind: PoolPolicy
    plural: poolpolicies
    shortNames:
    - pp
    singular: poolpolicy
  scope: Cluster
  version: v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: ballast
  name: ballast
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ballast.bonny.run
  resources:
  - poolpolicies
  verbs:
  - "*"
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: ballast
  name: ballast
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ballast
subjects:
- kind: ServiceAccount
  name: ballast
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: ballast
  name: ballast
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: ballast
  name: ballast
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ballast
  template:
    metadata:
      labels:
        k8s-app: ballast
    spec:
      volumes:
      - name: ballast-operator-sa-keys
        secret:
          secretName: ballast-operator-sa-keys
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/gcp.json
        - name: MIX_ENV
          value: prod
        - name: BONNY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: BONNY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BONNY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: BONNY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        image: quay.io/coryodaniel/ballast
        name: ballast
        volumeMounts:
        - name: ballast-operator-sa-keys
          mountPath: /credentials
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: ballast
