apiVersion: ballast.bonny.run/v1
kind: PoolPolicy
metadata:
  name: ballast-example
spec:
  projectId: ${project}
  location: ${location}
  clusterName: ${cluster}
  poolName: ${source_pool}
  cooldownSeconds: 30
  managedPools:
    - poolName: ${managed_pool_1}
      minimumInstances: 1
      minimumPercent: 25
      location: ${location}
    - poolName: ${managed_pool_2}
      minimumInstances: 1
      minimumPercent: 25
      location: ${location}
