apiVersion: ballast.bonny.run/v1
kind: "PoolPolicy"
metadata:
  name: ballast-example
spec:
  projectId: ${project}
  location: ${location}
  clusterName: ${cluster}
  poolName: ${source_pool}
  cooldownSeconds: 30
  autoEvictionEnabled: true # every 120 seconds for now, given ballast.bonny.run/v1/evictAfter: SECONDS
  targetPools:
  - poolName: ${target_autoscaling_pool}
    minimumInstances: 1
    targetCapacityPercent: 20
    location: ${location}
  - poolName: ${target_fixed_pool}
    minimumInstances: 2
    targetCapacityPercent: 20
    location: ${location}
