apiVersion: ballast.bonny.run/v1
kind: PoolPolicy
metadata:
  name: ballast-example
spec:
  projectId: ${project}
  location: ${location}
  clusterName: ${cluster}
  poolName: ${source_pool}
  cooldownSeconds: 30
  enableAutoEviction: true
  targetPools:
  - poolName: ${target_pool_1}
    minimumInstances: 1
    targetCapacityPercent: 25
    location: ${location}
  - poolName: ${target_pool_2}
    minimumInstances: 1
    targetCapacityPercent: 25
    location: ${location}
